{% set version = "5.02" %}

package:
  name: sl
  version:  {{ version }}

source:
  url: https://github.com/mtoyoda/sl/archive/{{ version }}.tar.gz
  sha256: 1e5996757f879c81f202a18ad8e982195cf51c41727d3fea4af01fdcbbb5563a

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    # we need a working terminal to test sl, which is not available on CI
    # rather test the existance of the binary
    - test -f ${PREFIX}/bin/sl

about:
  home: https://github.com/mtoyoda/sl
  license: Other
  license_file: LICENSE
  summary: 'Display animations aimed to correct users who accidentally enter sl instead of ls'

extra:
  recipe-maintainers:
    - jjhelmus
