travis:
  secure:
    BINSTAR_TOKEN: jixTzwPDXpnSdFSjpZ1qCDp68u3Z4VTSqYz33DgDluYGOB7QaBPbvqTF2DJ8YRcm3vQVT3tHuvetVoTBrWzXCPyNh6pAJfnLR0MY4KEFlYsBD95i8VG/hcmZAaHQmurQjWXrER/gvwGsSQkbdgVrMC4VQQdP1EN8MmTnbhNzcwwhuqywM/vYKSELjDjEgfvJAc7vsRV6FH1WmVHQT+OpNPrNbC7aR50a2VtDX5cwgqARlq7H0sWnXgfJI6+800OvJ/uYrxK0E03YbCO0TuNb690AXnykn7OAEc7y7r7koUmq5M0c6mCtVqaJVENpPVgDtnqx2ysmL6gxvbZkjI5YVPjf0MED/nybSJE3V1O1fTdkopoMwtTuXbMXoDiJIinyfDvvnBpCv1CkVRjbdhg7BYOohEMr/bnaOmSfmCqLwIxmZahzH6WMu6IPQy+ZCb1ppSQBHIzY9d5W1+RrgZWHp3QQZeFjP2y2E8nrmZtRqyFNQRSrPin42sx3OZOhM8/toPUjs20ZhwgvqGdNQ6en3Gm9dDapZqCym+FnRvqy9dYRLLNf//HlkxpZY8r5si/sXanUYCEbiUrVnZ/6zXBWNsxYwNIqqQ44huPcrebUolGgLcmvKd2fxFRAOCP52oli4Dx3DyKowBQoLPmlDo6w6Wstu9hArMdLVAeOhA+QdNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
