travis:
  secure:
    BINSTAR_TOKEN: n8Ug4MRZzhMnL7LOCpIWNMpUGeUca+4DEBTD2SWru2k521B/9h/fEEjV6yDXOM/eDhLwV1PT0/8JFW0oao1DG12bq3owPsKBqXv8z+sr2RzBCRXhASZjailGGl7oGkr5qsTrstktSqFGrUA4gkxT4D1XU+VRyunbqWI2oDO2eFud6Nt5vxmPxpDoP3h6AkXcaNZKKOODwAonZYiSJlQOVkn8RRBq2c316ovgIjskt/nDfMSVQ5du71+r8kRRIdIeEi07trJJvEYUHhFqJOAYEcM29n/k4gJ/2o91wwqN9MtzBL03KjYp5vFoIkowi1EObS9sFS0OJFBmFSVTsJPamhtlHM8wd1F9GO79x/cNtmOxu0/tMzFryS2jF+RMV35/KJvBqB43iaXUQ86JUYZ3lRvIxAyTORdMiJI8CVSueegWrVf567nSLfD8VGbWsdnPBH6eiUbqxG7HCBE9HfkdSYkEgEdGEpJctJC+xpjbOYT8DghmqJa+QW588vm6DSO+BoIKeBCstb4zbtG4Iq4FMRqywVivQnqXrcA3z3RlF62wocZaH/nOwnwRBnhsNWJoApx4DiUwpmQ+rvL/1pRaEhIlsrM5TRlNkXRHb6g/ihDzO4mvPYMYe7usUDT1i+oiOkjrD4XE/Erkd2oN0Fb5zI2W6ZxVlvs4pDUBset5AoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
