travis:
  secure:
    BINSTAR_TOKEN: tQfblxUwGh2QuAcOVfur7dy1zKi6xbxejnAwW4JuZPRVm5zmbfnks41foUaL1Sz7Xf/cmy1PmFtBoXmAwg5nDc5RcKpP2XTQXDmz5DInOQ/n3IxuMlhQB/zbB+pifokZc2flnxqJHhIHaquZ9e8eneO08I7ahT51jhYMQ1J1G1HWIvktfpoN+OX/zuB2Mpm3e+dXx6R5nbyJLZZc+MJWrNIBrRFq6foD871rKlRfc2WrEl7wutdcQTM+DV7uvURoBkLW/XUoVHX45071S0Kzi+mBru6UHSVQBT48MtsTv3Bp7dNkorYaiUIdh6RGXmvmJ1D4c5pbtvvumM/cz1r8pAPuhSSY1FAfHBdVTUYjp1km6Qqw03iQ6UjCrFls8dGY0YHUaU8xhak9a5S6qByOTZxJSptatiK8BTrLoB/jPvVXf4vYH4J9o0dOQjdeb7cy28RZvQiI5LQgN6FwSTBuvNR88AVYhhXpQjI/pG4MR7VCd6PFpx+iKM5d1Eu13ZbXj+Qs3axTRVVi3rjZBa3z/MWqfhgReQlPsgIWMp6a39GdH9B/hHgC4j7xLAnSz0RlGWlStWLQiMirtEtgrsmDhZjs6xa3G0rglyOk6UYwVnvhqU+uSugauNiqUqL3rLJFkYcZdkxcZyyfEDZw3eQ25yXdJmS6Jik4YfXeo8HRazM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
